version: '3'

dotenv: ['.env']

includes:
  api: ./packages/api

tasks:
  init:
    desc: initialize project
    cmds:
      - task: cert

  author:
    desc: display author
    cmds:
      - echo 'Romain BELLANDE'

  cert:
    desc: install certificates
    cmds:
      - mkcert -install
      - mkcert -cert-file traefik/certs/local-cert.pem -key-file traefik/certs/local-key.pem "tog.localhost" "*.tog.localhost"
