version: '3'

tasks:
  console:
    desc: execute console
    cmds:
      - docker-compose exec api bash -c "npm run console:dev -- {{ .ARGS }}"

  migration:create:
    desc: execute console
    cmds:
      - task: console
        vars:
          ARGS: db migration:create {{ .CLI_ARGS }}

  migration:up:
    desc: migrate up to the latest version
    cmds:
      - task: console
        vars:
          ARGS: db migration:up

  seeder:run:
    desc: execute seeder
    cmds:
      - task: console
        vars:
          ARGS: db seeder:run

  test:unit:
    desc: execute unit tests
    cmds:
      - npx nx run api:test

  test:e2e:
    desc: execute e2e tests
    env:
      NX_PORT: 8086
      NX_DATABASE_URL: postgres://pguser:pgpass@localhost:5451/tog
    cmds:
     - npx newman run ./packages/api/postman/tog.postman_collection.json -e ./packages/api/postman/tog.local.postman_environment.json

  lint:fix:
    desc: fix lint issues
    cmds:
     - npx nx run api:lint --fix
