name: Tog API CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'packages/api/**'

jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [20.x]
          package: [api]

      steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        - name: Install dependencies
          run: pnpm install

    test-unit:
        runs-on: ubuntu-latest

        steps:
          - name: execute tests
            run: npx nx run api:test

          - name: execute lint
            run: npx nx run api:lint

    tests-e2e:
      runs-on: ubuntu-latest

      container: node:20-alpine

      services:
        postgres:
          image: postgres:15.2-alpine3.17
          env:
            POSTGRES_DB: tog
          ports:
            - 5432/tcp

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        - name: run server and execute e2e tests
          run: npm run api:e2e
          env:
            NX_DATABASE_URL: postgres://postgres:${{ job.services.mongodb.ports[5432] }}/tog
            NX_PORT: 8086
